import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import MatchProvider from "../_store/game-context";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

import "./globals.css";
import "../_assets/icon.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} p-4`}>
        <section className="rounded-32 bg-secondary-dark-800 text-white w-[1512px] p-4">
          <MatchProvider>{children}</MatchProvider>
        </section>
      </body>
    </html>
  );
}
